const listaDeJogos = [
  "Angry Birds Trilogy",
  "Assassin's Creed II",
  "Brazucas 23 (PES 2013)",
  "Call of Duty: Advanced Warfare",
  "Call of Duty: Black Ops II",
  "Call of Duty: Ghosts",
  "Call of Duty 2",
  "Crysis 2",
  "Dante's Inferno",
  "Disney Universe",
  "Far Cry 3",
  "FIFA 19",
  "Forza Horizon",
  "GTA V",
  "Halo 4",
  "Metal Slug 3",
  "Metal Slug X",
  "Metro 2033",
  "Mortal Kombat",
  "Need for Speed: Most Wanted",
  "Pac-Man",
  "PES 2018",
  "Resident Evil 4",
  "Sonic & Sega All-Stars Racing",
  "Spider-Man: Shattered Dimensions",
  "Super Street Fighter IV",
  "Emulador Super Nitendo",
  "Black",
];
